{
  description = "nxtermd — terminal multiplexer with proper separation of concerns";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.11";
    flake-utils.url = "github:numtide/flake-utils";

    # wfvm provides the qemu + OVMF for the Windows test environment
    # (testenv/windows), folded into this flake's dev shell and `image` package
    # below. Pinned because the qemu/OVMF pairing is load-bearing (see
    # testenv/windows/session.md issue #2). Deliberately does not follow our
    # nixpkgs — wfvm pins nixos-23.11 internally.
    wfvm.url = "git+https://git.m-labs.hk/M-Labs/wfvm?rev=61caa6d2bc42640eca92cf829da6fe592a73cf48";
  };

  outputs = { self, nixpkgs, flake-utils, wfvm }:
    {
      homeManagerModules.default = import ./nix/home-manager.nix { nxterm = self; };
    } //
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        # Windows test environment (testenv/windows), folded into this flake.
        # x86_64-linux only (wfvm constraint); gated where used.
        isLinuxX86 = system == "x86_64-linux";

        wintestImage =
          if isLinuxX86
          then import ./testenv/windows/image.nix { inherit pkgs wfvm; }
          else null;

        # wfvm's qemu + the SPICE/SSH tooling the wintest-* scripts call.
        wintestPackages = pkgs.lib.optionals isLinuxX86 ((with pkgs; [
          virt-viewer openssh sshpass swtpm socat coreutils
        ]) ++ [ wfvm.lib.utils.qemu ]);

        wintestOvmfFd = "${wfvm.lib.utils.OVMF.fd}/FV/OVMF.fd";

        # Read version from dist/.version (generated by `make version`).
        # Falls back to git short rev or "dev".
        version =
          if builtins.pathExists ./dist/.version
          then builtins.replaceStrings ["\n"] [""] (builtins.readFile ./dist/.version)
          else if self ? shortRev then self.shortRev
          else if self ? dirtyShortRev then self.dirtyShortRev
          else "dev";

        nxtermd = pkgs.buildGoModule {
          pname = "nxtermd";
          inherit version;
          src = ./.;
          vendorHash = "sha256-gYFKr6x24vNpcnyEY8wBsWnPi7Wa/NEcIBh0EmZ5nCU=";
          subPackages = [ "cmd/nxtermd" "cmd/nxterm" "cmd/nxtermctl" ];
          env.CGO_ENABLED = 0;
          ldflags = [ "-s" "-w" "-X main.version=${version}" ];

          # The TUI embeds dist/changelog.txt at compile time.
          preBuild = ''
            echo "${version}: nix build" > dist/changelog.txt
          '';
        };

        mkRpm = dist: pkgs.stdenv.mkDerivation {
          pname = "nxtermd-rpm-${dist}";
          inherit version;
          dontUnpack = true;
          nativeBuildInputs = [ pkgs.nfpm ];

          buildPhase = ''
            # Stage binaries and service file
            cp ${nxtermd}/bin/nxtermd .
            cp ${nxtermd}/bin/nxterm .
            cp ${nxtermd}/bin/nxtermctl .
            cp ${./dist/nxtermd.service} nxtermd.service

            # Read version from the built binary
            export VERSION=$(./nxtermd --version 2>&1 | awk '{print $NF}')
            export GOARCH="${pkgs.go.GOARCH}"
            export DIST=".${dist}"
            ${pkgs.envsubst}/bin/envsubst < ${./dist/nfpm.yaml} > nfpm.yaml

            nfpm package --packager rpm --config nfpm.yaml
          '';

          installPhase = ''
            mkdir -p $out
            cp *.rpm $out/
          '';
        };
      in
      {
        packages = {
          default = nxtermd;

          rpm = pkgs.symlinkJoin {
            name = "nxtermd-rpms-${version}";
            paths = [ (mkRpm "fc43") (mkRpm "el9") ];
          };
        } // pkgs.lib.optionalAttrs isLinuxX86 {
          # Windows test base image; built on demand by wintest-start.
          image = wintestImage;
        };

        devShells.default = pkgs.mkShell {
          name = "nxterm-dev";

          packages = (with pkgs; [
            bash
            gnumake

            # Server + Frontend + termctl (Go)
            go
            gopls
            gotools  # goimports, etc.
            delve    # Go debugger
            gcc      # C/C++ compiler for cgo

            # Protocol debugging: NDJSON over a Unix socket
            jq
            netcat-gnu  # nc for manual socket interaction

            # Version control
            git

            # Sandbox
            bubblewrap

            # vhs
            vhs
            ubuntu-classic

          ]) ++ wintestPackages;

          shellHook = ''
            export CODEX_HOME=$PWD/.codex-home
            export CLAUDE_CONFIG_DIR=$PWD/.claude-config
            export PATH="$PWD/.local/bin:$PATH"
            export GOPATH="$PWD/.local/go"
            export GOCACHE="$PWD/.local/var/cache/go"
            export NIX_SHELL=nxtermd
            ${pkgs.lib.optionalString isLinuxX86 ''
            # Windows test environment (testenv/windows) wired into this shell.
            export WINTEST_OVMF_FD="${wintestOvmfFd}"
            export PATH="$PWD/testenv/windows/bin:$PATH"
            ''}
            echo
            echo "entering nxterm dev environment"
            echo "  * go  $(go version)"
            echo "  * gcc $(gcc --version | awk 'NR==1{print $NF}')"
            ${pkgs.lib.optionalString isLinuxX86 ''echo "  * wintest wired (testenv/windows)"''}
            if [ -z "$IN_SANDBOXED_SHELL" ]; then
              export IN_SANDBOXED_SHELL=1
              exec bwrap \
                --ro-bind / / \
                --bind "$PWD" "$PWD" \
                --bind "$HOME/.cache" "$HOME/.cache" \
                --bind "/tmp" "/tmp" \
                --dev-bind /dev /dev \
                --proc /proc \
                --unshare-pid \
                --die-with-parent \
                --setenv IN_SANDBOXED_SHELL 1 \
                -- bash -i
            fi
          '';

        };
      }
    );
}

